import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"
import hero from 'public/assets/hero.png'
export default function Home() {
  return (
    <>

      <main>
        <div className={styles.container}>
          <Head>
            <title>Tarefa+ | ORGANIZE SUAS TAREFAS</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <div className={styles.logoContent}>
              <Image className={styles.hero}src={hero}
              priority alt='Logo'></Image>
            </div>
            <h1 className={styles.title}>
              Sistema feito para você <br />
              Organizar seus estudos e tarefas
            </h1>
            <div className={styles.infoContent}>
                <section className={styles.box}>
                  <span>+12 posts</span>
                </section>
                <section className={styles.box}>
                  <span>+20 comentarios</span>
                </section>

            </div>
          </main>
        </div>

      </main>
    </>
  )
}
